Adding new strats + JSON schema
mangrovedao/mangrove-deployments pull request #63
Opened 2024-01-10 16:27 UTC by maxencerb

2024-01-11 07:51 UTC, espendk requested changes

2024-01-11 07:51 UTC, espendk commented on src/assets/strats/v2.0.0/MangroveOrder-Router.json
> +  "version": "2.0.0",
This is a deployment of a pre-release, not the actual v2.0.0, right?
If so, this version number (and the folder name) should reflect that pre-release version number.

2024-01-11 07:51 UTC, espendk commented on src/assets/contract.schema.json
Good idea to add a schema. However, this repo is currently immature and in flux, so the format will likely change (it actually changed while you where writing this), so I think we should add the schema after the format has stabilized.

2024-01-16 13:33 UTC, espendk approved these changes

2024-01-16 14:25 UTC, lnist approved these changes

2024-01-16 14:25 UTC, merged